export const LOADING_TARIF = 'LOADING_TARIF'
export const ERROR_TARIF = 'ERROR_TARIF'
export const GET_ALL_TARIFS = 'GET_ALL_TARIFS'
export const GET_ALL_TARIFS_WHITHOUT_LOADING = 'GET_ALL_TARIFS_WHITHOUT_LOADING'