export const LOADING_PARTNER = 'LOADING_PARTNER'
export const ERROR_PARTNER = 'ERROR_PARTNER'
export const GET_ALL_PARTNERS = 'GET_ALL_PARTNERS'
export const GET_ALL_PARTNERS_WITHOUT_LOADING = 'GET_ALL_PARTNERS_WITHOUT_LOADING'